export interface CountryConfig {
  code: string;
  name: string;
  flag: string;
  currency: { code: string; symbol: string; name: string };
  language: { code: string; name: string; isRTL: boolean };
  timezone: string;
  phoneFormat: string;
  phoneLength: number;
  paymentMethods: { id: string; name: string }[];
  categories: string[];
  minimumFeeFloor: number;
  taxRate: number;
  taxName: string;
}

export const COUNTRIES: Record<string, CountryConfig> = {
  NG: {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Africa/Lagos',
    phoneFormat: '+234 XXX XXX XXXX',
    phoneLength: 11,
    paymentMethods: [
      { id: 'paystack', name: 'Paystack' },
      { id: 'flutterwave', name: 'Flutterwave' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
      'Fashion & Tailoring', 'Agriculture',
    ],
    minimumFeeFloor: 100,
    taxRate: 0.075,
    taxName: 'VAT',
  },
  KE: {
    code: 'KE',
    name: 'Kenya',
    flag: '🇰🇪',
    currency: { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Africa/Nairobi',
    phoneFormat: '+254 XXX XXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'mpesa', name: 'M-Pesa' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Agriculture', 'Entertainment', 'Transportation',
    ],
    minimumFeeFloor: 20,
    taxRate: 0.16,
    taxName: 'VAT',
  },
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    currency: { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Africa/Johannesburg',
    phoneFormat: '+27 XX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'payfast', name: 'PayFast' },
      { id: 'yoco', name: 'Yoco' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.15,
    taxName: 'VAT',
  },
  GH: {
    code: 'GH',
    name: 'Ghana',
    flag: '🇬🇭',
    currency: { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Africa/Accra',
    phoneFormat: '+233 XXX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'paystack', name: 'Paystack' },
      { id: 'flutterwave', name: 'Flutterwave' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Agriculture', 'Entertainment', 'Transportation',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.15,
    taxName: 'VAT',
  },
  US: {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    currency: { code: 'USD', symbol: '$', name: 'US Dollar' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'America/New_York',
    phoneFormat: '+1 (XXX) XXX-XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.08,
    taxName: 'Sales Tax',
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currency: { code: 'GBP', symbol: '£', name: 'British Pound' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Europe/London',
    phoneFormat: '+44 XXXX XXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.30,
    taxRate: 0.20,
    taxName: 'VAT',
  },
  IN: {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    currency: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Asia/Kolkata',
    phoneFormat: '+91 XXXXX XXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'razorpay', name: 'Razorpay' },
      { id: 'upi', name: 'UPI' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
      'Tutoring', 'Event Planning',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.18,
    taxName: 'GST',
  },
  MW: {
    code: 'MW',
    name: 'Malawi',
    flag: '🇲🇼',
    currency: { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Africa/Blantyre',
    phoneFormat: '+265 XXXX XXXXXX',
    phoneLength: 9,
    paymentMethods: [
      { id: 'paychangu', name: 'PayChangu' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Agriculture',
      'Food & Dining', 'Beauty & Wellness', 'Technology',
      'Transportation', 'Entertainment',
    ],
    minimumFeeFloor: 200,
    taxRate: 0.165,
    taxName: 'VAT',
  },
  TZ: {
    code: 'TZ',
    name: 'Tanzania',
    flag: '🇹🇿',
    currency: { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Africa/Dar_es_Salaam',
    phoneFormat: '+255 XXX XXX XXX',
    phoneLength: 9,
    paymentMethods: [
      { id: 'mpesa', name: 'M-Pesa' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Agriculture',
      'Food & Dining', 'Beauty & Wellness', 'Technology',
      'Transportation', 'Entertainment', 'Tourism',
    ],
    minimumFeeFloor: 500,
    taxRate: 0.18,
    taxName: 'VAT',
  },
  UG: {
    code: 'UG',
    name: 'Uganda',
    flag: '🇺🇬',
    currency: { code: 'UGX', symbol: 'UGX', name: 'Ugandan Shilling' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'Africa/Kampala',
    phoneFormat: '+256 XXX XXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'mpesa', name: 'M-Pesa' },
      { id: 'airtel', name: 'Airtel Money' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Agriculture',
      'Food & Dining', 'Beauty & Wellness', 'Technology',
      'Transportation', 'Entertainment',
    ],
    minimumFeeFloor: 500,
    taxRate: 0.18,
    taxName: 'VAT',
  },
  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    currency: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
    language: { code: 'en', name: 'English', isRTL: true },
    timezone: 'Asia/Dubai',
    phoneFormat: '+971 XX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
      'Logistics', 'Tourism',
    ],
    minimumFeeFloor: 1,
    taxRate: 0.05,
    taxName: 'VAT',
  },
  EG: {
    code: 'EG',
    name: 'Egypt',
    flag: '🇪🇬',
    currency: { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
    language: { code: 'ar', name: 'Arabic', isRTL: true },
    timezone: 'Africa/Cairo',
    phoneFormat: '+20 XXX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'fawry', name: 'Fawry' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.14,
    taxName: 'VAT',
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    currency: { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar' },
    language: { code: 'en', name: 'English', isRTL: false },
    timezone: 'America/Toronto',
    phoneFormat: '+1 XXX-XXX-XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.13,
    taxName: 'HST',
  },
  FR: {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    language: { code: 'fr', name: 'French', isRTL: false },
    timezone: 'Europe/Paris',
    phoneFormat: '+33 X XX XX XX XX',
    phoneLength: 9,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.20,
    taxName: 'VAT',
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    language: { code: 'de', name: 'German', isRTL: false },
    timezone: 'Europe/Berlin',
    phoneFormat: '+49 XXX XXXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.19,
    taxName: 'VAT',
  },
};

export const CATEGORY_ICONS: Record<string, string> = {
  'Beauty & Wellness': 'sparkles',
  'Healthcare': 'heart-pulse',
  'Automotive': 'car',
  'Food & Dining': 'utensils',
  'Home Services': 'home',
  'Education': 'graduation-cap',
  'Technology': 'monitor',
  'Entertainment': 'music',
  'Transportation': 'truck',
  'Fashion & Tailoring': 'scissors',
  'Agriculture': 'leaf',
  'Legal & Financial': 'scale',
  'Real Estate': 'building',
  'Event Planning': 'calendar',
  'Tutoring': 'book-open',
  'Logistics': 'package',
  'Tourism': 'map',
};

export const CATEGORY_GRADIENTS: Record<string, [string, string]> = {
  'Beauty & Wellness': ['#EC4899', '#F43F5E'],
  'Healthcare': ['#10B981', '#059669'],
  'Automotive': ['#3B82F6', '#6366F1'],
  'Food & Dining': ['#F97316', '#EF4444'],
  'Home Services': ['#14B8A6', '#06B6D4'],
  'Education': ['#0EA5E9', '#3B82F6'],
  'Technology': ['#8B5CF6', '#A855F7'],
  'Entertainment': ['#7C3AED', '#8B5CF6'],
  'Transportation': ['#EAB308', '#F59E0B'],
  'Fashion & Tailoring': ['#EC4899', '#D946EF'],
  'Agriculture': ['#84CC16', '#22C55E'],
  'Legal & Financial': ['#64748B', '#6B7280'],
  'Real Estate': ['#F59E0B', '#D97706'],
  'Event Planning': ['#A855F7', '#7C3AED'],
  'Tutoring': ['#0EA5E9', '#2563EB'],
  'Logistics': ['#F97316', '#EA580C'],
  'Tourism': ['#06B6D4', '#0891B2'],
};
