import type { CurrencyConfig } from './currencies';
import type { LanguageConfig } from './languages';

export interface PaymentMethodConfig {
  id: string;
  name: string;
  icon: string;
}

export interface CountryConfig {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  domain: string;
  currency: CurrencyConfig;
  language: LanguageConfig;
  timezone: string;
  phoneFormat: string;
  phoneLength: number;
  paymentMethods: PaymentMethodConfig[];
  categories: string[];
  minimumFeeFloor: number;
  taxRate: number;
  taxName: string;
  dateFormat: string;
  timeFormat: '12h' | '24h';
  weekStartsOn: 0 | 1;
  legalTermsUrl: string;
  privacyUrl: string;
  isRTL: boolean;
  subdomain: string;
}

import { CURRENCIES } from './currencies';
import { LANGUAGES } from './languages';

export const COUNTRIES: Record<string, CountryConfig> = {
  US: {
    code: 'US',
    name: 'United States',
    nativeName: 'United States',
    flag: '🇺🇸',
    domain: 'us.afribook.com',
    currency: CURRENCIES.USD,
    language: LANGUAGES.en,
    timezone: 'America/New_York',
    phoneFormat: '+1 (XXX) XXX-XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe', icon: 'credit-card' },
      { id: 'paypal', name: 'PayPal', icon: 'paypal' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.08,
    taxName: 'Sales Tax',
    dateFormat: 'MM/dd/yyyy',
    timeFormat: '12h',
    weekStartsOn: 0,
    legalTermsUrl: 'https://us.afribook.com/legal/terms',
    privacyUrl: 'https://us.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'us',
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    nativeName: 'Canada',
    flag: '🇨🇦',
    domain: 'ca.afribook.com',
    currency: CURRENCIES.CAD,
    language: LANGUAGES.en,
    timezone: 'America/Toronto',
    phoneFormat: '+1 XXX-XXX-XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe', icon: 'credit-card' },
      { id: 'interac', name: 'Interac', icon: 'bank' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.13,
    taxName: 'HST',
    dateFormat: 'yyyy-MM-dd',
    timeFormat: '12h',
    weekStartsOn: 0,
    legalTermsUrl: 'https://ca.afribook.com/legal/terms',
    privacyUrl: 'https://ca.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'ca',
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    nativeName: 'United Kingdom',
    flag: '🇬🇧',
    domain: 'gb.afribook.com',
    currency: CURRENCIES.GBP,
    language: LANGUAGES.en,
    timezone: 'Europe/London',
    phoneFormat: '+44 XXXX XXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe', icon: 'credit-card' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.30,
    taxRate: 0.20,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://gb.afribook.com/legal/terms',
    privacyUrl: 'https://gb.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'gb',
  },
  IN: {
    code: 'IN',
    name: 'India',
    nativeName: 'भारत',
    flag: '🇮🇳',
    domain: 'in.afribook.com',
    currency: CURRENCIES.INR,
    language: LANGUAGES.en,
    timezone: 'Asia/Kolkata',
    phoneFormat: '+91 XXXXX XXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'razorpay', name: 'Razorpay', icon: 'credit-card' },
      { id: 'cashfree', name: 'Cashfree', icon: 'bank' },
      { id: 'upi', name: 'UPI', icon: 'smartphone' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
      'Tutoring', 'Event Planning',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.18,
    taxName: 'GST',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://in.afribook.com/legal/terms',
    privacyUrl: 'https://in.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'in',
  },
  NG: {
    code: 'NG',
    name: 'Nigeria',
    nativeName: 'Nigeria',
    flag: '🇳🇬',
    domain: 'ng.afribook.com',
    currency: CURRENCIES.NGN,
    language: LANGUAGES.en,
    timezone: 'Africa/Lagos',
    phoneFormat: '+234 XXX XXX XXXX',
    phoneLength: 11,
    paymentMethods: [
      { id: 'paystack', name: 'Paystack', icon: 'credit-card' },
      { id: 'flutterwave', name: 'Flutterwave', icon: 'bank' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
      'Fashion & Tailoring', 'Agriculture',
    ],
    minimumFeeFloor: 100,
    taxRate: 0.075,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://ng.afribook.com/legal/terms',
    privacyUrl: 'https://ng.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'ng',
  },
  KE: {
    code: 'KE',
    name: 'Kenya',
    nativeName: 'Kenya',
    flag: '🇰🇪',
    domain: 'ke.afribook.com',
    currency: CURRENCIES.KES,
    language: LANGUAGES.en,
    timezone: 'Africa/Nairobi',
    phoneFormat: '+254 XXX XXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'mpesa', name: 'M-Pesa', icon: 'smartphone' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Agriculture', 'Entertainment', 'Transportation',
    ],
    minimumFeeFloor: 20,
    taxRate: 0.16,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://ke.afribook.com/legal/terms',
    privacyUrl: 'https://ke.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'ke',
  },
  MW: {
    code: 'MW',
    name: 'Malawi',
    nativeName: 'Malawi',
    flag: '🇲🇼',
    domain: 'mw.afribook.com',
    currency: CURRENCIES.MWK,
    language: LANGUAGES.en,
    timezone: 'Africa/Blantyre',
    phoneFormat: '+265 XXXX XXXXXX',
    phoneLength: 9,
    paymentMethods: [
      { id: 'paychangu', name: 'PayChangu', icon: 'smartphone' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Agriculture',
      'Food & Dining', 'Beauty & Wellness', 'Technology',
      'Transportation', 'Entertainment',
    ],
    minimumFeeFloor: 200,
    taxRate: 0.165,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://mw.afribook.com/legal/terms',
    privacyUrl: 'https://mw.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'mw',
  },
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    nativeName: 'South Africa',
    flag: '🇿🇦',
    domain: 'za.afribook.com',
    currency: CURRENCIES.ZAR,
    language: LANGUAGES.en,
    timezone: 'Africa/Johannesburg',
    phoneFormat: '+27 XX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'payfast', name: 'PayFast', icon: 'credit-card' },
      { id: 'yoco', name: 'Yoco', icon: 'smartphone' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.15,
    taxName: 'VAT',
    dateFormat: 'yyyy/MM/dd',
    timeFormat: '24h',
    weekStartsOn: 0,
    legalTermsUrl: 'https://za.afribook.com/legal/terms',
    privacyUrl: 'https://za.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'za',
  },
  EG: {
    code: 'EG',
    name: 'Egypt',
    nativeName: 'مصر',
    flag: '🇪🇬',
    domain: 'eg.afribook.com',
    currency: CURRENCIES.EGP,
    language: LANGUAGES.ar,
    timezone: 'Africa/Cairo',
    phoneFormat: '+20 XXX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'fawry', name: 'Fawry', icon: 'bank' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.14,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 0,
    legalTermsUrl: 'https://eg.afribook.com/legal/terms',
    privacyUrl: 'https://eg.afribook.com/legal/privacy',
    isRTL: true,
    subdomain: 'eg',
  },
  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    nativeName: 'الإمارات العربية المتحدة',
    flag: '🇦🇪',
    domain: 'ae.afribook.com',
    currency: CURRENCIES.AED,
    language: LANGUAGES.en,
    timezone: 'Asia/Dubai',
    phoneFormat: '+971 XX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe', icon: 'credit-card' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
      'Logistics', 'Tourism',
    ],
    minimumFeeFloor: 1,
    taxRate: 0.05,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://ae.afribook.com/legal/terms',
    privacyUrl: 'https://ae.afribook.com/legal/privacy',
    isRTL: true,
    subdomain: 'ae',
  },
  GH: {
    code: 'GH',
    name: 'Ghana',
    nativeName: 'Ghana',
    flag: '🇬🇭',
    domain: 'gh.afribook.com',
    currency: CURRENCIES.GHS,
    language: LANGUAGES.en,
    timezone: 'Africa/Accra',
    phoneFormat: '+233 XXX XXX XXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'paystack', name: 'Paystack', icon: 'credit-card' },
      { id: 'flutterwave', name: 'Flutterwave', icon: 'bank' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Agriculture', 'Entertainment', 'Transportation',
    ],
    minimumFeeFloor: 5,
    taxRate: 0.15,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://gh.afribook.com/legal/terms',
    privacyUrl: 'https://gh.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'gh',
  },
  TZ: {
    code: 'TZ',
    name: 'Tanzania',
    nativeName: 'Tanzania',
    flag: '🇹🇿',
    domain: 'tz.afribook.com',
    currency: CURRENCIES.TZS,
    language: LANGUAGES.en,
    timezone: 'Africa/Dar_es_Salaam',
    phoneFormat: '+255 XXX XXX XXX',
    phoneLength: 9,
    paymentMethods: [
      { id: 'mpesa', name: 'M-Pesa', icon: 'smartphone' },
      { id: 'tigo', name: 'Tigo Pesa', icon: 'smartphone' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Agriculture',
      'Food & Dining', 'Beauty & Wellness', 'Technology',
      'Transportation', 'Entertainment', 'Tourism',
    ],
    minimumFeeFloor: 500,
    taxRate: 0.18,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://tz.afribook.com/legal/terms',
    privacyUrl: 'https://tz.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'tz',
  },
  UG: {
    code: 'UG',
    name: 'Uganda',
    nativeName: 'Uganda',
    flag: '🇺🇬',
    domain: 'ug.afribook.com',
    currency: CURRENCIES.UGX,
    language: LANGUAGES.en,
    timezone: 'Africa/Kampala',
    phoneFormat: '+256 XXX XXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'mpesa', name: 'M-Pesa', icon: 'smartphone' },
      { id: 'airtel', name: 'Airtel Money', icon: 'smartphone' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Agriculture',
      'Food & Dining', 'Beauty & Wellness', 'Technology',
      'Transportation', 'Entertainment',
    ],
    minimumFeeFloor: 500,
    taxRate: 0.18,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://ug.afribook.com/legal/terms',
    privacyUrl: 'https://ug.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'ug',
  },
  FR: {
    code: 'FR',
    name: 'France',
    nativeName: 'France',
    flag: '🇫🇷',
    domain: 'fr.afribook.com',
    currency: CURRENCIES.EUR,
    language: LANGUAGES.fr,
    timezone: 'Europe/Paris',
    phoneFormat: '+33 X XX XX XX XX',
    phoneLength: 9,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe', icon: 'credit-card' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.20,
    taxName: 'VAT',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://fr.afribook.com/legal/terms',
    privacyUrl: 'https://fr.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'fr',
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    nativeName: 'Deutschland',
    flag: '🇩🇪',
    domain: 'de.afribook.com',
    currency: CURRENCIES.EUR,
    language: LANGUAGES.de,
    timezone: 'Europe/Berlin',
    phoneFormat: '+49 XXX XXXXXXX',
    phoneLength: 10,
    paymentMethods: [
      { id: 'stripe', name: 'Stripe', icon: 'credit-card' },
    ],
    categories: [
      'Home Services', 'Healthcare', 'Education', 'Technology',
      'Food & Dining', 'Beauty & Wellness', 'Automotive',
      'Legal & Financial', 'Real Estate', 'Entertainment',
    ],
    minimumFeeFloor: 0.50,
    taxRate: 0.19,
    taxName: 'VAT',
    dateFormat: 'dd.MM.yyyy',
    timeFormat: '24h',
    weekStartsOn: 1,
    legalTermsUrl: 'https://de.afribook.com/legal/terms',
    privacyUrl: 'https://de.afribook.com/legal/privacy',
    isRTL: false,
    subdomain: 'de',
  },
};
