export interface CurrencyConfig {
  code: string;
  symbol: string;
  name: string;
  nativeName: string;
  decimalPlaces: number;
  format: string;
  exchangeRate: number;
}

export const CURRENCIES: Record<string, CurrencyConfig> = {
  USD: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    nativeName: 'US Dollar',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 1,
  },
  CAD: {
    code: 'CAD',
    symbol: 'CA$',
    name: 'Canadian Dollar',
    nativeName: 'Dollar Canadien',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 1.36,
  },
  GBP: {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound',
    nativeName: 'Pound Sterling',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 0.79,
  },
  EUR: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    nativeName: 'Euro',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 0.92,
  },
  INR: {
    code: 'INR',
    symbol: '₹',
    name: 'Indian Rupee',
    nativeName: 'भारतीय रुपया',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 83.0,
  },
  NGN: {
    code: 'NGN',
    symbol: '₦',
    name: 'Nigerian Naira',
    nativeName: 'Naira',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 1550,
  },
  KES: {
    code: 'KES',
    symbol: 'KSh',
    name: 'Kenyan Shilling',
    nativeName: 'Shilingi ya Kenya',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 145,
  },
  MWK: {
    code: 'MWK',
    symbol: 'MK',
    name: 'Malawian Kwacha',
    nativeName: 'Kwacha ya Malawi',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 1730,
  },
  ZAR: {
    code: 'ZAR',
    symbol: 'R',
    name: 'South African Rand',
    nativeName: 'Rand',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 18.5,
  },
  EGP: {
    code: 'EGP',
    symbol: 'E£',
    name: 'Egyptian Pound',
    nativeName: 'جنيه مصري',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 49.0,
  },
  AED: {
    code: 'AED',
    symbol: 'د.إ',
    name: 'UAE Dirham',
    nativeName: 'درهم إماراتي',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 3.67,
  },
  GHS: {
    code: 'GHS',
    symbol: 'GH₵',
    name: 'Ghanaian Cedi',
    nativeName: 'Cedi',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 15.3,
  },
  TZS: {
    code: 'TZS',
    symbol: 'TSh',
    name: 'Tanzanian Shilling',
    nativeName: 'Shilingi ya Tanzania',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 2550,
  },
  UGX: {
    code: 'UGX',
    symbol: 'USh',
    name: 'Ugandan Shilling',
    nativeName: 'Shilingi ya Uganda',
    decimalPlaces: 2,
    format: 'symbol amount',
    exchangeRate: 3700,
  },
  XAF: {
    code: 'XAF',
    symbol: 'FCFA',
    name: 'Central African CFA Franc',
    nativeName: 'Franc CFA',
    decimalPlaces: 0,
    format: 'amount symbol',
    exchangeRate: 620,
  },
  XOF: {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    nativeName: 'Franc CFA',
    decimalPlaces: 0,
    format: 'amount symbol',
    exchangeRate: 620,
  },
};
