export interface CurrencyConfig {
  code: string;
  symbol: string;
  name: string;
  nativeName: string;
  decimalPlaces: number;
  format: string;
  exchangeRate: number;
}

export const CURRENCIES: Record<string, CurrencyConfig> = {
  // ─── Major Global ──────────────────────────────────────────
  USD: { code: 'USD', symbol: '$', name: 'US Dollar', nativeName: 'US Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1 },
  EUR: { code: 'EUR', symbol: '€', name: 'Euro', nativeName: 'Euro', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 0.92 },
  GBP: { code: 'GBP', symbol: '£', name: 'British Pound', nativeName: 'Pound Sterling', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 0.79 },
  JPY: { code: 'JPY', symbol: '¥', name: 'Japanese Yen', nativeName: '円', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 155 },
  CNY: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', nativeName: '人民币', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 7.25 },
  CHF: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', nativeName: 'Franken', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 0.88 },
  CAD: { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', nativeName: 'Dollar Canadien', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1.36 },
  AUD: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1.53 },
  NZD: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1.65 },
  SGD: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1.35 },
  HKD: { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', nativeName: '港幣', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 7.82 },
  // ─── Americas ──────────────────────────────────────────────
  BRL: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', nativeName: 'Real', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 4.95 },
  MXN: { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso', nativeName: 'Peso', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 17.2 },
  ARS: { code: 'ARS', symbol: 'AR$', name: 'Argentine Peso', nativeName: 'Peso', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 890 },
  CLP: { code: 'CLP', symbol: 'CL$', name: 'Chilean Peso', nativeName: 'Peso', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 920 },
  COP: { code: 'COP', symbol: 'COL$', name: 'Colombian Peso', nativeName: 'Peso', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 3950 },
  PEN: { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', nativeName: 'Sol', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3.75 },
  CRC: { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', nativeName: 'Colón', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 510 },
  PAB: { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', nativeName: 'Balboa', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1 },
  GTQ: { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', nativeName: 'Quetzal', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 7.8 },
  HNL: { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', nativeName: 'Lempira', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 24.8 },
  NIO: { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', nativeName: 'Córdoba', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 36.8 },
  CUP: { code: 'CUP', symbol: '₱', name: 'Cuban Peso', nativeName: 'Peso', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 24 },
  DOP: { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', nativeName: 'Peso', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 56 },
  JMD: { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 157 },
  TTD: { code: 'TTD', symbol: 'TT$', name: 'Trinidad Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 6.8 },
  HTG: { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', nativeName: 'Gourde', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 132 },
  BOB: { code: 'BOB', symbol: 'Bs', name: 'Bolivian Boliviano', nativeName: 'Boliviano', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 6.9 },
  PYG: { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani', nativeName: 'Guaraní', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 7300 },
  UYU: { code: 'UYU', symbol: 'UY$', name: 'Uruguayan Peso', nativeName: 'Peso', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 39 },
  GYD: { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 209 },
  SRD: { code: 'SRD', symbol: 'SR$', name: 'Surinamese Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 37 },
  BZD: { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 2 },
  // ─── Caribbean (EC Dollar) ────────────────────────────────
  XCD: { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 2.7 },
  AWG: { code: 'AWG', symbol: 'Afl', name: 'Aruban Florin', nativeName: 'Florin', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1.79 },
  BBD: { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 2 },
  BSD: { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1 },
  // ─── Europe ────────────────────────────────────────────────
  SEK: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', nativeName: 'Krona', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 10.5 },
  NOK: { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', nativeName: 'Krone', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 10.8 },
  DKK: { code: 'DKK', symbol: 'kr', name: 'Danish Krone', nativeName: 'Krone', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 6.85 },
  PLN: { code: 'PLN', symbol: 'zł', name: 'Polish Złoty', nativeName: 'Złoty', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 4.0 },
  CZK: { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', nativeName: 'Koruna', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 23.0 },
  HUF: { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', nativeName: 'Forint', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 360 },
  RON: { code: 'RON', symbol: 'lei', name: 'Romanian Leu', nativeName: 'Leu', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 4.6 },
  BGN: { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', nativeName: 'Лев', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 1.8 },
  HRK: { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', nativeName: 'Kuna', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 6.9 },
  RSD: { code: 'RSD', symbol: 'din', name: 'Serbian Dinar', nativeName: 'Динар', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 108 },
  UAH: { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', nativeName: 'Гривня', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 41.0 },
  ISK: { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', nativeName: 'Króna', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 137 },
  ALL: { code: 'ALL', symbol: 'L', name: 'Albanian Lek', nativeName: 'Leku', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 94 },
  MKD: { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', nativeName: 'Денар', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 56 },
  BAM: { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Mark', nativeName: 'Конвертибилна марка', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 1.8 },
  MDL: { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', nativeName: 'Leu', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 18 },
  GEL: { code: 'GEL', symbol: '₾', name: 'Georgian Lari', nativeName: 'ლარი', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 2.7 },
  // ─── Middle East ───────────────────────────────────────────
  AED: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', nativeName: 'درهم إماراتي', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3.67 },
  SAR: { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', nativeName: 'ريال', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3.75 },
  QAR: { code: 'QAR', symbol: 'QR', name: 'Qatari Riyal', nativeName: 'ريال', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3.64 },
  KWD: { code: 'KWD', symbol: 'KD', name: 'Kuwaiti Dinar', nativeName: 'دينار', decimalPlaces: 3, format: 'symbol amount', exchangeRate: 0.31 },
  BHD: { code: 'BHD', symbol: 'BD', name: 'Bahraini Dinar', nativeName: 'دينار', decimalPlaces: 3, format: 'symbol amount', exchangeRate: 0.38 },
  OMR: { code: 'OMR', symbol: '﷼', name: 'Omani Rial', nativeName: 'ريال', decimalPlaces: 3, format: 'symbol amount', exchangeRate: 0.38 },
  JOD: { code: 'JOD', symbol: 'JD', name: 'Jordanian Dinar', nativeName: 'دينار', decimalPlaces: 3, format: 'symbol amount', exchangeRate: 0.71 },
  LBP: { code: 'LBP', symbol: 'L£', name: 'Lebanese Pound', nativeName: 'ليرة', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 89500 },
  ILS: { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', nativeName: 'שקל', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3.7 },
  TRY: { code: 'TRY', symbol: '₺', name: 'Turkish Lira', nativeName: 'Lira', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 30.5 },
  IQD: { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', nativeName: 'دينار', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 1310 },
  IRR: { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', nativeName: 'ریال', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 42000 },
  SYP: { code: 'SYP', symbol: 'S£', name: 'Syrian Pound', nativeName: 'ليرة', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 13000 },
  YER: { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', nativeName: 'ريال', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 250 },
  AFN: { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', nativeName: 'افغانی', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 72 },
  // ─── South Asia ────────────────────────────────────────────
  INR: { code: 'INR', symbol: '₹', name: 'Indian Rupee', nativeName: 'भारतीय रुपया', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 83.0 },
  BDT: { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', nativeName: 'টাকা', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 110 },
  PKR: { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', nativeName: 'روپیہ', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 278 },
  NPR: { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', nativeName: 'रुपैयाँ', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 133 },
  LKR: { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', nativeName: 'රුපියල්', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 310 },
  MVR: { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', nativeName: 'ރިވާ', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 15.4 },
  // ─── Southeast Asia ────────────────────────────────────────
  THB: { code: 'THB', symbol: '฿', name: 'Thai Baht', nativeName: 'บาท', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 35.5 },
  MYR: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', nativeName: 'Ringgit', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 4.70 },
  IDR: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', nativeName: 'Rupiah', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 15800 },
  PHP: { code: 'PHP', symbol: '₱', name: 'Philippine Peso', nativeName: 'Peso', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 56.0 },
  VND: { code: 'VND', symbol: '₫', name: 'Vietnamese Đồng', nativeName: 'Đồng', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 24500 },
  KHR: { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', nativeName: 'រៀល', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 4050 },
  MMK: { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', nativeName: 'ကျပ်', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 2100 },
  LAK: { code: 'LAK', symbol: '₭', name: 'Lao Kip', nativeName: 'ກີບ', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 21800 },
  BND: { code: 'BND', symbol: 'B$', name: 'Brunei Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1.35 },
  TWD: { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', nativeName: '元', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 31.5 },
  KRW: { code: 'KRW', symbol: '₩', name: 'South Korean Won', nativeName: '원', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 1350 },
  MOP: { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca', nativeName: '澳門幣', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 8.0 },
  // ─── Central Asia ──────────────────────────────────────────
  KZT: { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', nativeName: 'Теңге', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 460 },
  UZS: { code: 'UZS', symbol: 'so\'m', name: 'Uzbekistani Som', nativeName: 'сўм', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 12300 },
  KGS: { code: 'KGS', symbol: 'сом', name: 'Kyrgyzstani Som', nativeName: 'Сом', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 89 },
  TJS: { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', nativeName: 'Сомонӣ', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 10.9 },
  TMT: { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', nativeName: 'Manat', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3.5 },
  MNT: { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', nativeName: 'Төгрөг', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 3400 },
  // ─── Africa ────────────────────────────────────────────────
  NGN: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', nativeName: 'Naira', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1550 },
  KES: { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', nativeName: 'Shilingi ya Kenya', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 145 },
  GHS: { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', nativeName: 'Cedi', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 15.3 },
  ZAR: { code: 'ZAR', symbol: 'R', name: 'South African Rand', nativeName: 'Rand', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 18.5 },
  EGP: { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', nativeName: 'جنيه مصري', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 49.0 },
  TZS: { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', nativeName: 'Shilingi ya Tanzania', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 2550 },
  UGX: { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', nativeName: 'Shilingi ya Uganda', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3700 },
  MWK: { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', nativeName: 'Kwacha ya Malawi', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1730 },
  RWF: { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', nativeName: 'Franc', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 1350 },
  ETB: { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', nativeName: 'ብር', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 56 },
  XAF: { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', nativeName: 'Franc CFA', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 620 },
  XOF: { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', nativeName: 'Franc CFA', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 620 },
  MAD: { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham', nativeName: 'درهم', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 10.0 },
  DZD: { code: 'DZD', symbol: 'DA', name: 'Algerian Dinar', nativeName: 'دينار', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 135 },
  TND: { code: 'TND', symbol: 'DT', name: 'Tunisian Dinar', nativeName: 'دينار', decimalPlaces: 3, format: 'amount symbol', exchangeRate: 3.1 },
  BWP: { code: 'BWP', symbol: 'P', name: 'Botswana Pula', nativeName: 'Pula', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 13.5 },
  MUR: { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', nativeName: 'रुपया', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 45 },
  SCR: { code: 'SCR', symbol: 'SRe', name: 'Seychellois Rupee', nativeName: 'Rupee', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 13.5 },
  SDG: { code: 'SDG', symbol: 'SD', name: 'Sudanese Pound', nativeName: 'جنيه', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 600 },
  ZMW: { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', nativeName: 'Kwacha', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 25 },
  MGA: { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', nativeName: 'Ariary', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 4600 },
  MZN: { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', nativeName: 'Metical', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 63 },
  LSL: { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', nativeName: 'Loti', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 18.5 },
  SZL: { code: 'SZL', symbol: 'E', name: 'Eswatini Lilangeni', nativeName: 'Lilangeni', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 18.5 },
  NAD: { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 18.5 },
  MRU: { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', nativeName: 'أوقية', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 40 },
  GMD: { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', nativeName: 'Dalasi', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 67 },
  GNF: { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', nativeName: 'Franc', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 8600 },
  SLL: { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', nativeName: 'Leone', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 24000 },
  LRD: { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 192 },
  BIF: { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', nativeName: 'Franc', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 2860 },
  ERN: { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', nativeName: 'ናቕፋ', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 15 },
  DJF: { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', nativeName: 'Franc', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 178 },
  KMF: { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', nativeName: 'Franc', decimalPlaces: 0, format: 'symbol amount', exchangeRate: 450 },
  AOA: { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', nativeName: 'Kwanza', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 830 },
  CDF: { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', nativeName: 'Franc', decimalPlaces: 2, format: 'amount symbol', exchangeRate: 2550 },
  SOS: { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', nativeName: 'Shilin', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 568 },
  SSP: { code: 'SSP', symbol: 'SSP', name: 'South Sudanese Pound', nativeName: 'Pound', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 1350 },
  // ─── Oceania ───────────────────────────────────────────────
  FJD: { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', nativeName: 'Dollar', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 2.25 },
  PGK: { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', nativeName: 'Kina', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 3.9 },
  WST: { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', nativeName: 'Tālā', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 2.7 },
  TOP: { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', nativeName: 'Paʻanga', decimalPlaces: 2, format: 'symbol amount', exchangeRate: 2.3 },
  VUV: { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', nativeName: 'Vatu', decimalPlaces: 0, format: 'amount symbol', exchangeRate: 119 },
};
