export interface LanguageConfig {
  code: string;
  name: string;
  nativeName: string;
  isRTL: boolean;
  countries: string[];
}

export const LANGUAGES: Record<string, LanguageConfig> = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    isRTL: false,
    countries: ['US', 'GB', 'NG', 'KE', 'MW', 'ZA', 'GH', 'TZ', 'UG', 'AE', 'AU', 'NZ', 'SG', 'CA', 'IE', 'JM', 'TT', 'BS', 'BB', 'BZ', 'GY', 'SR', 'FJ', 'PG', 'BW', 'NA', 'LS', 'SZ', 'MU', 'SC', 'HK', 'LR'],
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    isRTL: false,
    countries: ['FR', 'CA', 'SN', 'CI', 'CM', 'BF', 'ML', 'NE', 'TD', 'TG', 'BJ', 'MG', 'RW', 'BI', 'CD', 'GA', 'CG', 'CF', 'GQ', 'DJ', 'KM'],
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    isRTL: false,
    countries: ['ES', 'MX', 'AR', 'CL', 'CO', 'PE', 'VE', 'EC', 'BO', 'PY', 'UY', 'CR', 'PA', 'GT', 'HN', 'SV', 'NI', 'CU', 'DO'],
  },
  pt: {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    isRTL: false,
    countries: ['PT', 'BR', 'AO', 'MZ', 'CV', 'GW', 'ST', 'TL'],
  },
  ar: {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    isRTL: true,
    countries: ['EG', 'AE', 'SA', 'MA', 'DZ', 'TN', 'JO', 'IQ', 'LB', 'SY', 'SD', 'MR', 'OM', 'QA', 'KW', 'BH', 'YE'],
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    isRTL: false,
    countries: ['IN'],
  },
  sw: {
    code: 'sw',
    name: 'Swahili',
    nativeName: 'Kiswahili',
    isRTL: false,
    countries: ['KE', 'TZ', 'UG', 'RW', 'BI', 'CD'],
  },
  yo: {
    code: 'yo',
    name: 'Yoruba',
    nativeName: 'Yorùbá',
    isRTL: false,
    countries: ['NG'],
  },
  ha: {
    code: 'ha',
    name: 'Hausa',
    nativeName: 'Hausa',
    isRTL: false,
    countries: ['NG'],
  },
  zu: {
    code: 'zu',
    name: 'Zulu',
    nativeName: 'isiZulu',
    isRTL: false,
    countries: ['ZA'],
  },
  af: {
    code: 'af',
    name: 'Afrikaans',
    nativeName: 'Afrikaans',
    isRTL: false,
    countries: ['ZA', 'NA', 'BW'],
  },
  de: {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    isRTL: false,
    countries: ['DE', 'AT', 'CH'],
  },
  bn: {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    isRTL: false,
    countries: ['BD'],
  },
  ur: {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    isRTL: true,
    countries: ['PK'],
  },
  ne: {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    isRTL: false,
    countries: ['NP'],
  },
  si: {
    code: 'si',
    name: 'Sinhala',
    nativeName: 'සිංහල',
    isRTL: false,
    countries: ['LK'],
  },
  am: {
    code: 'am',
    name: 'Amharic',
    nativeName: 'አማርኛ',
    isRTL: false,
    countries: ['ET'],
  },
  so: {
    code: 'so',
    name: 'Somali',
    nativeName: 'Soomaali',
    isRTL: false,
    countries: ['SO', 'DJ'],
  },
  ti: {
    code: 'ti',
    name: 'Tigrinya',
    nativeName: 'ትግርኛ',
    isRTL: false,
    countries: ['ER'],
  },
  ig: {
    code: 'ig',
    name: 'Igbo',
    nativeName: 'Igbo',
    isRTL: false,
    countries: ['NG'],
  },
  th: {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    isRTL: false,
    countries: ['TH'],
  },
  vi: {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    isRTL: false,
    countries: ['VN'],
  },
  id: {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    isRTL: false,
    countries: ['ID'],
  },
  ms: {
    code: 'ms',
    name: 'Malay',
    nativeName: 'Bahasa Melayu',
    isRTL: false,
    countries: ['MY', 'BN'],
  },
  tl: {
    code: 'tl',
    name: 'Tagalog',
    nativeName: 'Tagalog',
    isRTL: false,
    countries: ['PH'],
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    isRTL: false,
    countries: ['JP'],
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    isRTL: false,
    countries: ['KR'],
  },
  zh: {
    code: 'zh',
    name: 'Chinese (Mandarin)',
    nativeName: '中文',
    isRTL: false,
    countries: ['CN', 'TW', 'HK', 'MO'],
  },
  tr: {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    isRTL: false,
    countries: ['TR'],
  },
  pl: {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    isRTL: false,
    countries: ['PL'],
  },
  ro: {
    code: 'ro',
    name: 'Romanian',
    nativeName: 'Română',
    isRTL: false,
    countries: ['RO', 'MD'],
  },
  hu: {
    code: 'hu',
    name: 'Hungarian',
    nativeName: 'Magyar',
    isRTL: false,
    countries: ['HU'],
  },
  cs: {
    code: 'cs',
    name: 'Czech',
    nativeName: 'Čeština',
    isRTL: false,
    countries: ['CZ'],
  },
  nl: {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    isRTL: false,
    countries: ['NL', 'BE'],
  },
  it: {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    isRTL: false,
    countries: ['IT'],
  },
  sv: {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    isRTL: false,
    countries: ['SE'],
  },
  he: {
    code: 'he',
    name: 'Hebrew',
    nativeName: 'עברית',
    isRTL: true,
    countries: ['IL'],
  },
  fa: {
    code: 'fa',
    name: 'Persian',
    nativeName: 'فارسی',
    isRTL: true,
    countries: ['IR'],
  },
  uk: {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    isRTL: false,
    countries: ['UA'],
  },
  ka: {
    code: 'ka',
    name: 'Georgian',
    nativeName: 'ქართული',
    isRTL: false,
    countries: ['GE'],
  },
  my: {
    code: 'my',
    name: 'Burmese',
    nativeName: 'မြန်မာ',
    isRTL: false,
    countries: ['MM'],
  },
  km: {
    code: 'km',
    name: 'Khmer',
    nativeName: 'ខ្មែរ',
    isRTL: false,
    countries: ['KH'],
  },
  lo: {
    code: 'lo',
    name: 'Lao',
    nativeName: 'ລາວ',
    isRTL: false,
    countries: ['LA'],
  },
  ps: {
    code: 'ps',
    name: 'Pashto',
    nativeName: 'پښتو',
    isRTL: true,
    countries: ['AF'],
  },
  tg: {
    code: 'tg',
    name: 'Tajik',
    nativeName: 'Тоҷикӣ',
    isRTL: false,
    countries: ['TJ'],
  },
  mn: {
    code: 'mn',
    name: 'Mongolian',
    nativeName: 'Монгол',
    isRTL: false,
    countries: ['MN'],
  },
  fi: {
    code: 'fi',
    name: 'Finnish',
    nativeName: 'Suomi',
    isRTL: false,
    countries: ['FI'],
  },
};
