import { COUNTRIES as WEB_COUNTRIES } from '../../src/lib/localization/countries';
import * as fs from 'fs';

const lines: string[] = [];
lines.push(`// AUTO-GENERATED from src/lib/localization/countries.ts (the web app's`);
lines.push(`// authoritative country data) — do not hand-edit. Previously this file`);
lines.push(`// only had 15 hand-maintained countries while web had 198, so the`);
lines.push(`// mobile app silently mispriced/miscurrencied every user outside those`);
lines.push(`// 15. Regenerate with: npx tsx mobile/scripts/generate-countries.ts`);
lines.push(``);
lines.push(`export interface CountryConfig {`);
lines.push(`  code: string;`);
lines.push(`  name: string;`);
lines.push(`  flag: string;`);
lines.push(`  currency: { code: string; symbol: string; name: string };`);
lines.push(`  language: { code: string; name: string; isRTL: boolean };`);
lines.push(`  timezone: string;`);
lines.push(`  phoneFormat: string;`);
lines.push(`  phoneLength: number;`);
lines.push(`  paymentMethods: { id: string; name: string }[];`);
lines.push(`  categories: string[];`);
lines.push(`  minimumFeeFloor: number;`);
lines.push(`  taxRate: number;`);
lines.push(`  taxName: string;`);
lines.push(`}`);
lines.push(``);
lines.push(`export const COUNTRIES: Record<string, CountryConfig> = {`);

const esc = (s: string) => JSON.stringify(s ?? '');

for (const code of Object.keys(WEB_COUNTRIES).sort()) {
  const c = WEB_COUNTRIES[code];
  lines.push(`  ${code}: {`);
  lines.push(`    code: ${esc(c.code)},`);
  lines.push(`    name: ${esc(c.name)},`);
  lines.push(`    flag: ${esc(c.flag)},`);
  lines.push(`    currency: { code: ${esc(c.currency.code)}, symbol: ${esc(c.currency.symbol)}, name: ${esc(c.currency.name)} },`);
  lines.push(`    language: { code: ${esc(c.language.code)}, name: ${esc(c.language.name)}, isRTL: ${c.language.isRTL ? 'true' : 'false'} },`);
  lines.push(`    timezone: ${esc(c.timezone)},`);
  lines.push(`    phoneFormat: ${esc(c.phoneFormat)},`);
  lines.push(`    phoneLength: ${c.phoneLength},`);
  lines.push(`    paymentMethods: ${JSON.stringify((c.paymentMethods ?? []).map((p) => ({ id: p.id, name: p.name })))},`);
  lines.push(`    categories: ${JSON.stringify(c.categories ?? [])},`);
  lines.push(`    minimumFeeFloor: ${c.minimumFeeFloor},`);
  lines.push(`    taxRate: ${c.taxRate},`);
  lines.push(`    taxName: ${esc(c.taxName)},`);
  lines.push(`  },`);
}

lines.push(`};`);
lines.push(``);
lines.push(`// Preserved from the original hand-written file — these are icon/color`);
lines.push(`// mappings for category tiles, not per-country data, so they're not`);
lines.push(`// part of the web->mobile country sync above.`);
lines.push(`export const CATEGORY_ICONS: Record<string, string> = {`);
lines.push(`  'Beauty & Wellness': 'sparkles',`);
lines.push(`  'Healthcare': 'heart-pulse',`);
lines.push(`  'Automotive': 'car',`);
lines.push(`  'Food & Dining': 'utensils',`);
lines.push(`  'Home Services': 'home',`);
lines.push(`  'Education': 'graduation-cap',`);
lines.push(`  'Technology': 'monitor',`);
lines.push(`  'Entertainment': 'music',`);
lines.push(`  'Transportation': 'truck',`);
lines.push(`  'Fashion & Tailoring': 'scissors',`);
lines.push(`  'Agriculture': 'leaf',`);
lines.push(`  'Legal & Financial': 'scale',`);
lines.push(`  'Real Estate': 'building',`);
lines.push(`  'Event Planning': 'calendar',`);
lines.push(`  'Tutoring': 'book-open',`);
lines.push(`  'Logistics': 'package',`);
lines.push(`  'Tourism': 'map',`);
lines.push(`};`);
lines.push(``);
lines.push(`export const CATEGORY_GRADIENTS: Record<string, [string, string]> = {`);
lines.push(`  'Beauty & Wellness': ['#EC4899', '#F43F5E'],`);
lines.push(`  'Healthcare': ['#10B981', '#059669'],`);
lines.push(`  'Automotive': ['#3B82F6', '#6366F1'],`);
lines.push(`  'Food & Dining': ['#F97316', '#EF4444'],`);
lines.push(`  'Home Services': ['#14B8A6', '#06B6D4'],`);
lines.push(`  'Education': ['#0EA5E9', '#3B82F6'],`);
lines.push(`  'Technology': ['#8B5CF6', '#A855F7'],`);
lines.push(`  'Entertainment': ['#7C3AED', '#8B5CF6'],`);
lines.push(`  'Transportation': ['#EAB308', '#F59E0B'],`);
lines.push(`  'Fashion & Tailoring': ['#EC4899', '#D946EF'],`);
lines.push(`  'Agriculture': ['#84CC16', '#22C55E'],`);
lines.push(`  'Legal & Financial': ['#64748B', '#6B7280'],`);
lines.push(`  'Real Estate': ['#F59E0B', '#D97706'],`);
lines.push(`  'Event Planning': ['#A855F7', '#7C3AED'],`);
lines.push(`  'Tutoring': ['#0EA5E9', '#2563EB'],`);
lines.push(`  'Logistics': ['#F97316', '#EA580C'],`);
lines.push(`  'Tourism': ['#06B6D4', '#0891B2'],`);
lines.push(`};`);
lines.push(``);

fs.writeFileSync(__dirname + '/../src/constants/countries.ts', lines.join('\n'));
console.log(`Wrote ${Object.keys(WEB_COUNTRIES).length} countries to mobile/src/constants/countries.ts`);
